name: JSON function
on:
    workflow_dispatch:
jobs:
    dump-value:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${CONTEXT}"
              env:
                    CONTEXT: ${{ toJSON(github) }}
